[package]
name = "OAAB_Data"
version = "2.2.2"
description = "A free-to-use asset repository for the Morrowind Community."
homepage = "https://www.nexusmods.com/morrowind/mods/49042"
repository = "https://github.com/Of-Ash-And-Blight/OAAB-Data"
authors = [
	"Anroha",
	"Axeljk",
	"Corsair",
	"Dallara",
	"Endoran",
	"Greatness7",
	"Hemaris",
	"Melchior Dahrk",
	"Merlord",
	"MwGek",
	"Olaf",
	"OperatorJack",
	"PikachunoTM",
	"R-Zero",
	"RedFurryDemon",
	"Remiros",
	"Revenorror",
	"Tewlwolow",
	"Wolli",
	"XeroFox",
]

[dependencies.mwse]
buildnumber = 3074

[tools.csse]
deprecated = [
	"AB_Furn_BoneSkelArmUpperL",
	"AB_Furn_BoneSkelArmUpperL.1",
	"AB_Misc_BoneSkelArmUpperL",
	"AB_Furn_BoneSkelArmUpperR",
	"AB_Furn_BoneSkelArmUpperR.1",
	"AB_Misc_BoneSkelArmUpperR",
	"AB_Furn_BoneSkelFootL",
	"AB_Furn_BoneSkelFootL.1",
	"AB_Misc_BoneSkelFootL",
	"AB_Furn_BoneSkelFootR",
	"AB_Furn_BoneSkelFootR.1",
	"AB_Misc_BoneSkelFootR",
	"AB_Furn_BoneSkelHandL",
	"AB_Furn_BoneSkelHand1L.1",
	"AB_Misc_BoneSkelHandL",
	"AB_Furn_BoneSkelHandR",
	"AB_Furn_BoneSkelHand1R.1",
	"AB_Misc_BoneSkelHandR",
	"AB_Furn_BoneSkelLegUpperL",
	"AB_Furn_BoneSkelLegUpperL.1",
	"AB_Misc_BoneSkelLegUpperL",
	"AB_Furn_BoneSkelLegUpperR",
	"AB_Furn_BoneSkelLegUpperR.1",
	"AB_Misc_BoneSkelLegUpperR",
	"AB_Furn_BoneSkelLegShinL",
	"AB_Furn_BoneSkelLegShinL.1",
	"AB_Misc_BoneSkelLegShinL",
	"AB_Furn_BoneSkelLegShinR",
	"AB_Furn_BoneSkelLegShinR.1",
	"AB_Misc_BoneSkelLegShinR",
	"AB_Furn_BoneSkelArmWristL",
	"AB_Furn_BoneSkelArmWristL.1",
	"AB_Misc_BoneSkelArmWristL",
	"AB_Furn_BoneSkelArmWristR",
	"AB_Furn_BoneSkelArmWristR.1",
	"AB_Misc_BoneSkelArmWristR",
	"AB_Misc_BoneSkelSkullNoJaw",
	"AB_light_BlueWater128",
	"AB_light_BlueWater256",
	"AB_light_BlueWater512",
	"AB_light_BlueWater768",
	"AB_Light_Red_768",
	"AB_lvl_DwemerIngredients",
	"AB_lvl_ScrollsEnchantedAll",
	"AB_Fx_Four01",
	"AB_w_WoodArrow",
	"AB_o_BoxFlourRespawn",
	"AB_Misc_ComPewterCup_01",
	"AB_In_DeScaffold_01",
	"AB_w_AshlBoneArrow",
	"AB_o_CorpseNecro_01",
	"AB_Furn_StaffMold_a",
	"AB_Furn_StaffHeater_a",
	"AB_In_WebTrap",
	"AB_Furn_Banner6th01",
	"AB_Furn_RedoranBanner03",
	"AB_Furn_RedoranBanner_01",
	"AB_Furn_RedoranBanner_02",
	"AB_Furn_ImpPlanter_01",
	"AB_bk_AlchemistBeginners",
	"AB_bk_AvoidingDanger",
	"AB_bk_AlchemistCompendium",
	"AB_bk_AlchemistCompendium1",
	"AB_bk_AlchemistCompendium2",
	"AB_bk_AlchemistCompendium3",
	"AB_bk_AlchemistCompendium4",
	"AB_bk_AlchemistCompendium5",
	"AB_bk_AlchemistCompendiumClosed",
	"AB_bk_AlchemistFauna",
	"AB_bk_AlchemistFaunaSolstheim",
	"AB_bk_AlchemistFlora1",
	"AB_bk_AlchemistFlora2",
	"AB_bk_AlchemistFlora3",
	"AB_bk_AlchemistFlora4",
	"AB_bk_AlchemistFlora5",
	"AB_bk_AlchemistFlora6",
	"AB_bk_AlchemistFloraMournhold",
	"AB_bk_AlchemistFloraClosed",
	"AB_bk_BlacksmithComplete",
	"AB_bk_DaedraLesser",
	"AB_bk_DaeshrineSurvey",
	"AB_bk_DunmerStrongholds",
	"AB_bk_DwemerRuins",
	"AB_bk_Guars",
	"AB_bk_GuideToEnchanting_sk",
	"AB_bk_NordSongs",
	"AB_bk_SayingsOfTamriel",
	"AB_bk_TombRegistry",
	"AB_Ex_RedPillarArobar",
	"AB_Ex_RedPillarLlethri",
	"AB_Ex_RedPillarMorvayn",
	"AB_Ex_RedPillarRamoran",
	"AB_Ex_RedPillarSarethi",
	"AB_Ex_RedPillarVenim",
	"AB_Furn_EnchantInfuser",
	"AB_Furn_EnchantMat",
	"AB_Furn_ImpFan01_a",
	"AB_Furn_PaintingTelMora",
	"AB_Furn_VaeStakeHead01",
	"AB_sc_AlchemyRecipe01",
	"AB_sc_AlchemyRecipe02",
	"AB_sc_AlchemyRecipe03",
	"AB_sc_AlchemyRecipe04",
	"AB_sc_AlchemyRecipe05",
	"AB_sc_AlchemyRecipe06",
	"AB_sc_AlchemyRecipe07",
	"AB_sc_AlchemyRecipe08",
	"AB_bk_AlchemistFloraSolstheim",
	"AB_bk_MarasTear",
	"AB_bk_WhiteGuar",
	"AB_bk_CrudeLimericks",
	"AB_bk_DiseaseBlight",
	"AB_Ex_RedWindow01",
	"AB_Ex_CranePlatLong",
	"AB_Ex_CranePlatMid",
	"AB_Ex_CranePlatShort",
	"AB_Info_CandlePlacement",
	"AB_Info_CaveScaffold",
	"AB_Info_ClimbingPicks",
	"AB_Info_DwrvChainJunction",
	"AB_Info_DwrvGrateStairs",
	"AB_Info_DwrvMachineKit",
	"AB_Info_DwrvNixieLights",
	"AB_Info_DwrvScaffold",
	"AB_Info_DwrvScaffoldLadders",
	"AB_Info_DwrvStencilTricks",
	"AB_Info_DwrvStove",
	"AB_Info_ImpChainPull",
	"AB_Info_KwamaAcidDrips",
	"AB_Info_KwamaEggBoom",
	"AB_Info_KwamaForagerTower",
	"AB_Info_LightRay",
	"AB_Info_ScamptallowCandles",
	"AB_Info_VelHiddenTowerDoor",
	"AB_bk_AlchemistFloraBloat",
	"AB_bk_BloatCultivation",
	"AB_bk_DiseaseCommon",
	"AB_bk_GuideToBretons",
	"AB_bk_GuideToOrcs",
	"AB_bk_ImperialEggMining",
	"AB_bk_Minerals",
	"AB_bk_AlchemistFlora",
	"AB_bk_AlchemistFloraClose",
	"AB_sc_AncestralGuidance",
	"AB_Misc_AshlFlute",
	"AB_IngCrea_SpiderVenom",
	"AB_o_TelChestLargeUni1",
	"AB_o_TelChestLargeUni2",
	"AB_o_TelChestLargeUni3",
	"AB_o_TelChestLargeUni4",
	"AB_In_CaveMoldFloorMushroom",
	"AB_lvl_SpiderVenom",
	"AB_Spider_s",
	AB_In_VelSmallRampLong01",
	"AB_Misc_PaperCrumpled",
	"AB_o_ComClosetThin",
	"AB_o_ComRchCabinet",
	"AB_Furn_ComRchFootstool",
	"AB_Furn_ComRchShelfSmall",
	"AB_Furn_ComRchTableTall",
	"AB_Furn_ComBarShelf",
]