[package]
name = "OAAB_Data"
version = "2.1.1"
description = "A free-to-use asset repository for the Morrowind Community."
homepage = "https://www.nexusmods.com/morrowind/mods/49042"
repository = "https://github.com/Of-Ash-And-Blight/OAAB-Data"
authors = [
	"Anroha",
	"Axeljk",
	"Corsair",
	"Dallara",
	"Endoran",
	"Greatness7",
	"Hemaris",
	"Melchior Dahrk",
	"Merlord",
	"MwGek",
	"Olaf",
	"OperatorJack",
	"PikachunoTM",
	"R-Zero",
	"RedFurryDemon",
	"Remiros",
	"Revenorror",
	"Tewlwolow",
	"Wolli",
	"XeroFox",
]

[dependencies.mwse]
buildnumber = 3074
